name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/deployment/
            if [ ! -d "back-hawtin-blog" ]; then
              git clone --depth=1 https://github.com/HawtinZeng/back-hawtin-blog
              cd back-hawtin-blog
            else
              cd back-hawtin-blog
              git fetch origin main
              git reset --hard origin/main
            fi
            whoami
            sudo docker ps
            sudo  docker rm -f back-blog
            sudo docker rmi  back-blog
            sudo docker build --build-arg dbUri=mongodb://120.53.232.99:10000/ --build-arg bucketName=visuals --build-arg databaseName=hawtin-blog --build-arg collectionName=blogs -t back-blog .
            sudo docker run -d --restart always -u root --name back-blog --network=host back-blog
